<div id="admins", class="row" ng-show="admins">
    <div class="table-container col-xs-12">
        <div class="row table-header">
            <div class="col-xs-12">
                <i class="fa fa-globe"></i>
                <span>Admins</span>
            </div>
        </div>
        <div class="row table-list">
            <div class="col-xs-12">
                <div class="row table-list-header">
                    <div class="col-xs-1">#</div>
                    <div class="col-xs-7">Name</div>
                </div>

                <div ng-class="{1:'even'}[$index%2]" class="row table-list-row" ng-repeat="admin in admins track by $index">
                    <div class="col-xs-1 text">[[$index+1]].</div>
                    <div class="col-xs-7 text">[[admin.name]]</div>
                    <div class="actions text-right col-xs-4">
                        <a ng-href="/dashboard/admin/[[admin.id]]" class="action-link">
                          <div class="action-icon">
                            <i class="fa fa-eye "></i>
                          </div>
                          <div class="action-text">View</div>
                        </a>
                        <a ng-show="!inProgress['admins'][$index] && {'INACTIVE':true}[admin.status]" href="#admins" ng-click="activate($index,'admins', true)"b class="action-link">
                          <div class="action-icon">
                            <i class="fa fa-user"></i>
                            <i class="fa fa-plus"></i>
                          </div>
                          <div class="action-text">Activate</div>
                        </a>
                        <a ng-show="!inProgress['admins'][$index] && {'ACTIVE':true}[admin.status]" href="#admins" ng-click="activate($index,'admins', false)" class="action-link">
                          <div class="action-icon">
                            <i class="fa fa-user"></i>
                            <i class="fa fa-minus"></i>
                          </div>
                          <div class="action-text">Deactivate</div>
                        </a>
                        <div class="action-link" ng-show="inProgress['admins'][$index]">
                            <div class="action-icon">
                                <i class="fa fa-cog fa-spin"></i>
                            </div>
                            <div class="action-text">Updating</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <div class="page" ng-show="admin_pages > 1">
            <ul class="pagination">
                <li class="arrow unavailable">
                    <a href="" ng-click="select_admin_page(-1)">&laquo;</a>
                </li>
                <li ng-repeat="page in range(admin_pages)" ng-class="getClass($index+1)">
                    <a href="" ng-click="select_admin_page($index+1)">[[$index+1]]</a>
                </li>
                <!-- <li class="unavailable">
                    <a href="">&hellip;</a>
                </li>  -->
                <li class="arrow">
                    <a href="" ng-click="select_admin_page(0)">&raquo;</a>
                </li>
            </ul>
        </div>
    </div>
</div>
