<div id="assign-mentee-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">
            <i class="fa fa-times"></i>
          </span>
          <span class="sr-only">Close</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Assign [[modal.mentee.name]] To A Mentor</h4>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-xs-12 form-group search-group">
            <input type="text" ng-model="search" placeholder="Enter a mentor's name..." class="form-control search-input"/>
            <i class="fa fa-search search-icon"></i>
          </div>
        </div>
        <div class="row table-container">
          <div class="col-xs-12 search-results-container table-list">
            <div class="row table-list-header">
                <div class="col-xs-1">#</div>
                <div class="col-xs-7">Name</div>
            </div>
            <div class="row table-list-row" ng-class="{1:'even'}[$index%2]" ng-repeat="mentor in mentors | filter: {name:search} track by $index">
              <div class="col-xs-1 text">[[$index+1]].</div>
              <div class="col-xs-7 text">[[mentor.name]]</div>
              <div class="actions text-right col-xs-4">
                <a ng-show="!inProgress['mentors'][$index]" ng-click="assignMentorToMentee($index,modal.menteeIdx)" href="#" class="action-link">
                  <div class="action-icon">
                    <i class="fa fa-group "></i>
                  </div>
                  <div class="action-text">Assign</div>
                </a>
                <div class="action-link" ng-show="inProgress['mentors'][$index]">
                    <div class="action-icon">
                        <i class="fa fa-cog fa-spin"></i>
                    </div>
                    <div class="action-text">Assigning</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
