<div id="view-note-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
        	<span aria-hidden="true">
        		<i class="fa fa-times"></i>
        	</span>
        	<span class="sr-only">Close</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">[[modal.note.name]]</h4>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-xs-12">[[modal.note.note]]</div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
