<?php $this->headScript()->prependFile($this->basePath() . '/js/admin.min.js') ?>
<div class="row" ng-controller="CreateAccountCtrl" ng-init="init()">
    <div class="col-xs-10 col-xs-offset-1">
        <div class="row">
            <div class="col-xs-12">
                <h1> Create Account </h1>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-8">
                <form class="create-account-form row" name="createAccountForm" ng-submit="createAccount()">
                    <div class="col-xs-12">
                        <div class="row" ng-show="success">
                            <div class="col-xs-12 error">
                                <div ng-show="msg" class="alert alert-success">[[msg]]</div>
                            </div>
                        </div>

                        <div class="row" ng-hide="success">
                            <div class="col-xs-12 error">
                                <div ng-show="createAccountForm.$dirty && msg" class="alert alert-warning">[[msg]]</div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group settings-col reminder-frequency col-xs-12">
                                <div class="row">
                                    <label class="col-sm-5">Account Type:</label>
                                    <div class="col-sm-7">
                                        <select ng-model="create.role_id" ng-options="r.id as r.name for r in roles" class="form-control" required></select>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group text-input col-xs-12">
                                <div class="row">
                                    <label class="col-xs-5">Name:</label>
                                    <div class="col-xs-7">
                                        <input class="form-control" type="text" name="name" ng-model="create.name" required/>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group text-input col-xs-12">
                                <div class="row">
                                    <label class="col-xs-5">Title:</label>
                                    <div class="col-xs-7">
                                        <input class="form-control" type="text" name="title" ng-model="create.title" required/>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group text-input col-xs-12">
                                <div class="row">
                                    <label class="col-xs-5">Phone Number:</label>
                                    <div class="col-xs-7">
                                        <input class="form-control" type="text" name="phoneNumber" ng-model="create.phoneNumber" required/>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group text-input col-xs-12">
                                <div class="row">
                                    <label class="col-xs-5">Email Address:</label>
                                    <div class="col-xs-7">
                                        <input class="form-control" type="text" name="email" ng-model="create.email" required/>
                                    </div>
                                </div>
                            </div>
                        </div>


                        <div class="row">
                            <div class="col-xs-12 settings-col">
                                <button type="submit" value="Create Account" class="btn btn-primary">
                                    <span ng-hide="inProgress">Create Account</span>
                                    <i class="fa fa-cog fa-spin" ng-show="inProgress"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-sm-4">
                <div class="alert alert-info create-account-info">
                    <i class="fa fa-info-circle"></i>
                    <span>A welcome email will be sent to the new account holder with a link to finish their account setup.  After following the link they will be prompted to provide a password. </span>
                </div>
            </div>
        </div>
    </div>
</div>
